version: '3.4'

services:
  identity.api:
    image: ${DOCKER_REGISTRY}identityapi
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile

  webstatus:
    image: ${DOCKER_REGISTRY}webstatus
    build:
      context: .
      dockerfile: src/WebApps/WebStatus/Dockerfile


  ocelotapigw:
    image: ${DOCKER_REGISTRY}ocelotapigw
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/OcelotApiGw/Dockerfile

